### ISSUE TITLE
开启消息确认,队列最后被消费的消息发回确认却还是显示unacked不释放

### ISSUE THREAD

**Issue by JackMask007** [aox-lei/scrapy-rabbitmq-scheduler#10]
在最后被消费的消息,消费完成后发送的确认消息不能生效,以本项目带的例子来做的测试
![1619746742(1)](https://user-images.githubusercontent.com/43439402/116638286-94b5d600-a998-11eb-9fdc-5735428adde5.png)
![1619746835(1)](https://user-images.githubusercontent.com/43439402/116638291-97b0c680-a998-11eb-8ca0-473f28996608.png)

**Comment by coder-fly** [comment]
最后几条消息(取决于设定的预读取量值)实际没有被ack，SaaS类的ack_message方法中在进行ack前判断力一下self.queue，当队列中Ready量为空时，这里会返回0(调用__len__方法)，但实际队列是有unack的消息，程序重启后unack的数据又回到队列中，周而复始，定义一个__bool__方法可以解决。

**Comment by JackMask007** [comment]
> 最后几条消息(取决于设定的预读取量值)实际没有被ack，SaaS类的ack_message方法中在进行ack前判断力一下self.queue，当队列中Ready量为空时，这里会返回0(调用__len__方法)，但实际队列是有unack的消息，程序重启后unack的数据又回到队列中，周而复始，定义一个__bool__方法可以解决。

**Comment by JackMask007** [comment]
> 最后几条消息（确定设定的预读取量值）实际没有被ack，SaaS类的ack_message方法中在进行ack前判断力一下self.queue，当处于中Ready量为空时，这里会返回0（调用__len__方法），但实际实际上是有unack的消息，程序重启后unack的数据又回到该中，周而复始，定义一个__bool__方法可以解决。
我之前通过在返回的__len__值+1解决了,感谢你的回复.
