### ISSUE TITLE
采集过程中如何重新返回队列

### ISSUE THREAD

**Issue by wangtengfei1002** [aox-lei/scrapy-rabbitmq-scheduler#5]
请问一下在采集过程中因为某些字段没有采集到，应该返回什么样的结果使其重新加入队列
列如
# 指定重试的http状态码(重新加回队列重试)
SCHEDULER_REQUEUE_ON_STATUS = [500]

**Comment by aox-lei** [comment]
可以直接yield这个请求阿就会重新跑阿
